# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
bot: 371175469:AAFZjsjbupLsvM4o7I0VPAADRd5cM_6-Y70
development:
  secret_key_base: 8e28380ada250ae07669e92f2301a07a504814210880cc92c1414906564f1055e3808185311f11ca7b0dd8740d892442c6d9a0f323f7b134c24fa330c1704155

test:
  secret_key_base: 12184ad5d1a40583237c376e2a5f159728998dec7511d8759dca831924c4bc4f1066bca573d0b500a8db6c10f2c66f6fb0229347f269df921f1eb34d284f5af0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
